services:
  backend:
    build: ./Clairvoyance/backend
    ports:
      - "8000:8000"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
  frontend:
    build: ./Clairvoyance/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
